name: Project CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set yaml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
#        env:
#          spring.datasource.url: ${{secrets.DB_HOST}}
#          spring.datasource.username : ${{secrets.DB_USERNAME}}
#          spring.datasource.password : ${{secrets.DB_PASSWORD}}


      - name : Grant perssion for Gradle
        run : chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: | 
          ./gradlew build -x test
#          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
        shell: bash

      - name: make build artifact
        uses: actions/upload-artifact@v4
        with:
          name: g25Server
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: g25Server
          path: build/libs/

      - name: Check if JAR file exists
        run: ls -alh build/libs/

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/*.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/g25Server.jar

          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          if pgrep -f g25Server.jar > /dev/null; then
            echo "서버 실행 중 - 종료 중..."
            pkill -f g25Server.jar
            sleep 5
          else
            echo "서버가 실행되지 않음 - 새로 시작."
          fi
          nohup java -jar /home/${{ secrets.EC2_USERNAME }}/g25Server.jar > /home/${{ secrets.EC2_USERNAME }}/app.log 2>&1 &
          EOF

          rm -f private_key.pem
