name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: Ubuntu 22.04


    steps:
    # Github Actions 러너에서 코드를 가져옴
    - name: Checkout
      uses: actions/checkout@v4

    #Java 설정
    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'

    # Gradle 설정
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v2
      with:
        gradle-version: '8.11.1'

    # Gradle 테스트 실행
    - name: Run Tests
      run: ./gradlew test --info

    # Gradle 빌드 실행
    - name: Build with Gradle
      run: ./gradlew build
